- name: Install NTP
  apt:
    name: ntp
    state: present

- name: Add the below lines to ntp config file
  blockinfile:
    path: /etc/ntp.conf
    state: present
    insertafter: "# Specify one or more NTP servers."
    block: |
      server 192.168.1.22 prefer

- name: Ensure ntp up and enabled
  service: 
    name: ntp
    state: restarted
    enabled: yes

- name: Install nfs service
  apt:
    name: nfs-common
    state: present

- name: Create directory for shared dir mounting
  file:
    path: /var/locally-mounted
    state: directory
    mode: '0755'

- name: Mount NFS directory
  ansible.posix.mount:
    path: /var/locally-mounted
    src: 192.168.1.22:/mnt/myshareddir
    fstype: nfs
    opts: rw,sync
    state: mounted