version: '3.7'
services:
  node-exporter:
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    image: prom/node-exporter

  prometheus:
    container_name: prometheus
    ports:
      - '9090:9090' #modify 9090 to your setup needs
    volumes:
      - '/var/lib/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml' #modify the path for your install location
    image: prom/prometheus

  grafana:
    container_name: grafana
    ports:
      - '3456:3000' #modify 3457 to your setup needs
    image: grafana/grafana