- name: Copy keyfile onto machine
  copy:
    src: keyfile
    dest: /root/keyfile
    owner: root
    group: root
    mode: 0400
    
- name: Create LUKS container (remains unchanged if it already exists)
  community.crypto.luks_device:
    device: /dev/sda
    state: present
    keyfile: /root/keyfile

- name: Add the below lines to crypttab
  blockinfile:
    path: /etc/crypttab
    state: present
    block: |
      sda_crypt      /dev/sda  /root/keyfile  luks

- name: Create a ext3 filesystem on disk
  filesystem:
    fstype: ext3
    dev: /dev/mapper/sda_crypt
    force: yes
    
- name: Create a directory for mounting if it does not exist
  ansible.builtin.file:
    path: /crypted
    state: directory
    mode: '0755'

- name: Add the below lines to fstab
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      /dev/mapper/sda_crypt  /crypted     ext3    nofail,x-systemd.device-timeout=1ms        0       2