- name: Install nfs service
  apt:
    name: nfs-common
    state: present

- name: Create directory for shared dir mounting
  file:
    path: /var/locally-mounted
    state: directory
    mode: '0755'

- name: Mount NFS directory
  ansible.posix.mount:
    path: /var/locally-mounted
    src: 192.168.1.22:/mnt/myshareddir
    fstype: nfs
    opts: rw,sync
    state: mounted